id: PF013B401
initial_creation_type: ocr
source_metadata:
  volumes:
    f82c5e01412c4a9abd49a8fa773be365:
      base_file: v038.txt
      image_group_id: I1PD95883
      title: དེ་བཞིན་གཤེགས་པ་བདུན་གྱི་སྔོན་གྱི་སྨོན་ལམ་གྱི་ཁྱད་པར་རྒྱས་པ།
      total_pages: 1044
      volume_number: 38
